name: Build - Linux GCC + MPICH + CUDA-NVCC11

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: source .github/workflows/dependencies/dependencies_nvcc11.sh
    - name: configure
      run: autoreconf -i && CUDA_CFLAGS="-I/usr/include/x86_64-linux-gnu/mpich/" ./configure --enable-cuda --with-cuda-dir=/usr/local/cuda
    - name: make
      run: make
    - name: make check
      run: make check
