name: Build - Linux GCC Serial

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: autoreconf -i && CC=gcc CXX=g++ MPICC=gcc MPICXX=g++ ./configure --enable-serial
    - name: make
      run: make
    - name: make check
      run: make check
